<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  drop files orBrowseSupported form_3a2f15_3</name>
   <tag></tag>
   <elementGuidId>2823110b-3f99-469a-bfa7-6e9af4865a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[1]/div/span/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-b4-dropzone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc3f8d91-2902-4c9a-92a0-685c64348ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-box-file drop-zone </value>
      <webElementGuid>1d363116-5157-4141-9fff-ccf5092c2648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-b4-dropzone</value>
      <webElementGuid>274414b6-bd7c-4ffd-8e18-abfe3f4f0b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file</value>
      <webElementGuid>7d583fdf-9abf-4304-b344-bc40c7c35a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-b4-dropzone&quot;)</value>
      <webElementGuid>b2c76b7c-9d89-4a73-b941-abd2329a912b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-b4-dropzone']</value>
      <webElementGuid>266d9945-5ac2-4196-9911-e6a6ab5c25e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-$b4']/div/div</value>
      <webElementGuid>04625d41-2b02-45cf-8b42-fc56af010bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Dokumen'])[1]/following::div[4]</value>
      <webElementGuid>7c1e0058-08ad-41da-af2a-6a76d989c133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>5b3a04dd-abea-47d3-af66-969ac9aa7d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b1-b4-b13-b4-dropzone' and (text() = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file' or . = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file')]</value>
      <webElementGuid>9344625b-3e2a-42a3-9d66-5e6b8192e6e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
