<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  drop files orBrowseSupported form_3a2f15_1</name>
   <tag></tag>
   <elementGuidId>1858afcb-e592-4acf-9008-63af58eee932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[1]/div/span/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-b4-dropzone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>091a9e03-752b-4d7c-8f7b-2d2de826801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-box-file drop-zone </value>
      <webElementGuid>a3687747-40c5-42f4-9f2b-468fe417031c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-b4-dropzone</value>
      <webElementGuid>f2d5e1a6-2d0a-45fd-aeea-4199e993127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file</value>
      <webElementGuid>f39d05c0-4a3c-4c9d-b57b-3b9d4923494c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-b4-dropzone&quot;)</value>
      <webElementGuid>57cf9478-404e-4dc2-b844-68a2059c1947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-b4-dropzone']</value>
      <webElementGuid>1437be68-0197-492f-b6cf-ec6f9230291d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-$b4']/div/div</value>
      <webElementGuid>3ca1a840-ed08-4667-8fc9-38a575f0792e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Dokumen'])[1]/following::div[4]</value>
      <webElementGuid>394423b0-55b9-47bb-bb36-45a39eef6e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>a4e4e620-9baa-4e75-a345-2981385265e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b1-b4-b13-b4-dropzone' and (text() = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file' or . = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file')]</value>
      <webElementGuid>ca370781-3e9a-4444-b7c2-abf596516c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
