<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiLantai 1Lantai 2Lantai 3</name>
   <tag></tag>
   <elementGuidId>3ff92846-c7a7-41b9-8077-f437c5c03fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[6]/aside/div[2]/div/div/form/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-Dropdown2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2ea87917-598b-4e8c-9b13-4c8474891510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>dae1f802-b4f9-4fce-b8d4-1927fcc9543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ddc55fe-67c6-4f5d-8182-3183f703fa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-Dropdown2</value>
      <webElementGuid>7c98f3f6-fee8-44bd-bf34-a06c3fd60b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiLantai 1Lantai 2Lantai 3</value>
      <webElementGuid>05e01a33-ed27-4282-8a21-48d0fe8f7732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-Dropdown2&quot;)</value>
      <webElementGuid>60042aea-e20a-48ed-bb10-f540559f4139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-b13-Dropdown2']</value>
      <webElementGuid>4a24b7ec-66d4-40fd-a06e-513c2dbb932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-Dropdown2-container']/select</value>
      <webElementGuid>9d665ea8-a304-4e9f-a80a-34692171c670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lantai'])[5]/following::select[1]</value>
      <webElementGuid>c367943b-d4ba-4c61-be2f-2e5093d9dcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keberadaan'])[10]/following::select[2]</value>
      <webElementGuid>bc13519b-c259-435e-a62b-6af891f2f3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baik'])[12]/preceding::select[1]</value>
      <webElementGuid>7c52c47e-e49c-4f11-92ff-606dc7d1fb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rusak'])[8]/preceding::select[1]</value>
      <webElementGuid>2ff4a741-7c30-417c-a4bf-0795f00202ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/aside/div[2]/div/div/form/div[2]/div/select</value>
      <webElementGuid>cdd35055-aa2f-4289-8b6b-4b63a3b887fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-b13-Dropdown2' and (text() = 'Pilih OpsiLantai 1Lantai 2Lantai 3' or . = 'Pilih OpsiLantai 1Lantai 2Lantai 3')]</value>
      <webElementGuid>22303852-1bff-4c94-9084-37062eadbd52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
