<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan_b3-l1-328_0-b2-TextArea_Remarks</name>
   <tag></tag>
   <elementGuidId>7fff5ef8-84cf-425c-9c3b-e31060cc68d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-328_0-b2-TextArea_Remarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[2]/div/div/div/div/div[3]/div[2]/form/div/div/div[2]/div/div/div[2]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b446a1e6-9708-4017-b0c0-b93984ac6e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>c323e9b3-6497-42bb-bf73-9da2815ccc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>82c9c8a5-1a02-45b0-a191-e7f20791a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>844574b0-57cd-4605-8a3d-1d275fa21749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-328_0-b2-TextArea_Remarks</value>
      <webElementGuid>ac317f5e-d6b4-4798-a13d-25f913544023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-328_0-b2-TextArea_Remarks&quot;)</value>
      <webElementGuid>7ce0bc7d-4a69-4c48-8430-0ea5fba3b276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l1-328_0-b2-TextArea_Remarks']</value>
      <webElementGuid>275be3d6-9d1c-4013-bf7b-4cdffa1f58b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-328_0-b2-b13-Column2']/span/textarea</value>
      <webElementGuid>ecfe88e1-648f-4a98-adf4-91de864bb875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00cf107d-711b-4c9b-a33c-b46822aa797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l1-328_0-b2-TextArea_Remarks']</value>
      <webElementGuid>640665f6-02ee-4272-8a74-c779d7ed4428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
