<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Assign</name>
   <tag></tag>
   <elementGuidId>a6f51e60-7cdb-41ea-bcde-89990973786a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div[2]/div[2]/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-rounded.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>649bb7f5-a8ab-499b-8b44-e3f5c342b702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-rounded btn-primary</value>
      <webElementGuid>f56c5e57-6465-44d5-af74-87918632439f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e48e9541-a0a7-4216-bd7a-849a5f82cdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign</value>
      <webElementGuid>e3cd4c91-4e9f-4374-ae27-95845d798927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-$b1&quot;)/div[@class=&quot;card-filter&quot;]/div[@class=&quot;display-flex align-items-center&quot;]/div[@class=&quot;display-flex justify-content-space-between align-items-center OSInline&quot;]/div[3]/button[@class=&quot;btn btn-rounded btn-primary&quot;]</value>
      <webElementGuid>12c1493a-cd2a-4efc-b8b6-accfb22b9468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>4e6b795f-0195-4ee5-99fb-ad5bfe8bfbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-$b1']/div/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>39d00944-b4cd-419e-be12-299377aa608d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::button[1]</value>
      <webElementGuid>890a3bf0-7e04-48d6-be49-943b693fea80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status :'])[1]/following::button[2]</value>
      <webElementGuid>f70f4da4-f138-409b-97c8-d1d874b88383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task ID'])[1]/preceding::button[1]</value>
      <webElementGuid>71b87ec8-0149-4738-8f5e-05a77db03e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Penugasan'])[1]/preceding::button[1]</value>
      <webElementGuid>234845f2-d3fd-4d61-81e4-425b036855bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assign']/parent::*</value>
      <webElementGuid>66b7cdb9-ecb2-4299-a418-fb80ce9fa97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>da68567b-a605-416f-9dcc-259618196c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Assign' or . = 'Assign')]</value>
      <webElementGuid>ae2b26a9-f174-4a72-a453-9192117cb96e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
