<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>3580cbef-ee97-4edc-bf40-585a06076e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.shadow-m.upload-file-button.ThemeGrid_Width2.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33ebc306-488c-4c1d-9bf5-6a79c7ef2a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary shadow-m upload-file-button ThemeGrid_Width2 ThemeGrid_MarginGutter</value>
      <webElementGuid>bea3dd46-0ab1-4d15-9b56-e2ac6da356c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07e63d19-2dd1-44d4-bf28-d9fde4bf496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>643b82cf-bacf-4632-83c8-9ae59c98f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-$b4&quot;)/div[@class=&quot;margin-top-base text-align-right&quot;]/button[@class=&quot;btn btn-primary shadow-m upload-file-button ThemeGrid_Width2 ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>3e0d1307-18fd-4d27-8b3c-6dc2b3a245e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[295]</value>
      <webElementGuid>1817d19e-5900-4e69-a0f4-9e0ce0281cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-$b4']/div[3]/button[2]</value>
      <webElementGuid>62a9e448-d664-4814-a042-449aef095983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[6]/following::button[1]</value>
      <webElementGuid>ed9619a4-0266-479d-af37-2823a2f90a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loremipsum1.pdf'])[2]/following::button[2]</value>
      <webElementGuid>0a2ed531-14bb-42b0-8a4b-3361a669d7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9471b929-b060-47e7-8bf9-92e460549a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>a44149d9-d8f9-4a75-ae82-c9b54d9dfc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
