<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Depan Kantor_osui-accordion-item__icon _8b3719</name>
   <tag></tag>
   <elementGuidId>201da224-ce9d-453c-ad4a-231c2eefd2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[2]/div/div/div[1]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.osui-accordion-item__icon.osui-accordion-item__icon--caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f67fde7d-4bbe-4622-a6c6-1006ee9e6728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__icon osui-accordion-item__icon--caret</value>
      <webElementGuid>80a5ffd0-aab3-49b8-9734-04d0897b28f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91a573b6-5bfe-4321-a7af-81cbf3c33215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-l2-189_0-b2-TitleWrapper&quot;)/div[@class=&quot;osui-accordion-item__icon osui-accordion-item__icon--caret&quot;]</value>
      <webElementGuid>03b64936-8c10-4802-a763-9807a505328b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-l2-189_0-b2-TitleWrapper']/div[2]</value>
      <webElementGuid>f392b620-6389-47cf-a0d6-03a5964c377a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>2a3f86a6-97a7-47ea-9c1b-b9b4de5d276e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
