<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_semarang utility_osui-accordion-item__i_e156f9</name>
   <tag></tag>
   <elementGuidId>99eecd70-b2ed-4bd9-9bcd-29548c48fdfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[2]/div/div/div[14]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-l2-192_13-b2-TitleWrapper > div.osui-accordion-item__icon.osui-accordion-item__icon--caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6069e2f-c66f-4e8c-a0b8-fe9fcad2e58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__icon osui-accordion-item__icon--caret</value>
      <webElementGuid>434dc8cf-0f8c-4b84-919a-17e3cc466235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7acb5e31-0ae1-4ec4-a5c4-97b42b223155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-l2-192_13-b2-TitleWrapper&quot;)/div[@class=&quot;osui-accordion-item__icon osui-accordion-item__icon--caret&quot;]</value>
      <webElementGuid>75100b9a-64b3-4ccf-a36f-3aefbf1e45c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-l2-192_13-b2-TitleWrapper']/div[2]</value>
      <webElementGuid>96e64ed7-c443-467b-b58b-73e11dc89adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]</value>
      <webElementGuid>a4c7d995-e5e5-44bd-ad53-b221bc202de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
