<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_KeberadaanPilih OpsiAdaTidak AdaLantai_7cd206</name>
   <tag></tag>
   <elementGuidId>431b0dd8-88ab-47df-9a2a-9be2dfbe2ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='b3-b1-b4-b13-Form2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-Form2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>bbf36222-961d-4549-bbfa-e9ecc5fa5e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form  OSFillParent</value>
      <webElementGuid>a8240730-e2e6-46e1-a3d8-feb7fcc6577f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-Form2</value>
      <webElementGuid>251411b2-14b5-49e5-94ac-fb8213596bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KeberadaanPilih OpsiAdaTidak AdaLantaiPilih OpsiLantai 1Lantai 2Lantai 3BaikRusakJumlahRegister GAPPilih OpsiAdaTidak AdaRegister ITPilih OpsiAdaTidak AdaStatusPilih OpsiAktifDisposalMutasiTidak TerpakaiKategori TemuanPilih OpsiRendahSedangTinggiCatatanDokumenUnggahBatalSimpan</value>
      <webElementGuid>f501eded-7243-43fd-8c2a-7978aa366813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-Form2&quot;)</value>
      <webElementGuid>586533b8-b38b-4542-848c-855c0d241324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='b3-b1-b4-b13-Form2']</value>
      <webElementGuid>23b5e51f-7ad0-4c45-80b0-a7306ccc03f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-$b13']/div/form</value>
      <webElementGuid>da129e74-560a-4429-a1d6-e17285fa5c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fasilitas - Motor'])[1]/following::form[1]</value>
      <webElementGuid>5611bc58-a364-48ee-817e-67166e6b6ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[3]/following::form[1]</value>
      <webElementGuid>49d90dad-0969-46ac-a5d0-d17e5b21ac45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/aside/div[2]/div/div/form</value>
      <webElementGuid>6a2e10da-52e0-400e-b2c2-b9d394460d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'b3-b1-b4-b13-Form2' and (text() = 'KeberadaanPilih OpsiAdaTidak AdaLantaiPilih OpsiLantai 1Lantai 2Lantai 3BaikRusakJumlahRegister GAPPilih OpsiAdaTidak AdaRegister ITPilih OpsiAdaTidak AdaStatusPilih OpsiAktifDisposalMutasiTidak TerpakaiKategori TemuanPilih OpsiRendahSedangTinggiCatatanDokumenUnggahBatalSimpan' or . = 'KeberadaanPilih OpsiAdaTidak AdaLantaiPilih OpsiLantai 1Lantai 2Lantai 3BaikRusakJumlahRegister GAPPilih OpsiAdaTidak AdaRegister ITPilih OpsiAdaTidak AdaStatusPilih OpsiAktifDisposalMutasiTidak TerpakaiKategori TemuanPilih OpsiRendahSedangTinggiCatatanDokumenUnggahBatalSimpan')]</value>
      <webElementGuid>7a0fec7a-a0e6-4f32-85da-faaaa684cafd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
