<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ruang Pantry_osui-accordion-item__icon _626b4a</name>
   <tag></tag>
   <elementGuidId>ca44a7db-d2dc-40e6-ac14-9c3d9cf533af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[2]/div/div/div[12]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-l2-220_11-b2-TitleWrapper > div.osui-accordion-item__icon.osui-accordion-item__icon--caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b332eec-9d91-4c24-bb70-8fac63e17fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-accordion-item__icon osui-accordion-item__icon--caret</value>
      <webElementGuid>bce99f8c-c792-4a5d-a612-57645e42b315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b50bd3b7-e88f-4cc2-97e4-ce670cac3eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-l2-220_11-b2-TitleWrapper&quot;)/div[@class=&quot;osui-accordion-item__icon osui-accordion-item__icon--caret&quot;]</value>
      <webElementGuid>f588b568-62d8-4ca2-8184-27c9d1450779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-l2-220_11-b2-TitleWrapper']/div[2]</value>
      <webElementGuid>e0552921-e785-4a0d-8573-bc2f40baa92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]</value>
      <webElementGuid>f034c5b5-42ad-4019-8061-c3d2977acf7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
