<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenggat Waktu Penyelesaian_b3-b3-b3-b_9a858d</name>
   <tag></tag>
   <elementGuidId>8514e2d3-49ee-4a24-b122-94129adb8e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b3-b4-TenggatWaktuPenyelesaian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[3]/div/div[2]/div/aside/div[2]/div/form/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e01768e7-886a-4a07-b781-95a54ff3ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>286a5106-4bd5-47d3-bb99-fa65ecb27cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>cb7a19ec-2032-499b-b053-2777374a76f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ad04d95-0ba8-459b-9454-6aa825c432e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b3-b4-TenggatWaktuPenyelesaian</value>
      <webElementGuid>91f8a7e4-4c8d-451e-8e3b-490a00280ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b3-b4-TenggatWaktuPenyelesaian&quot;)</value>
      <webElementGuid>d8393e21-f252-4db1-8320-20331c5eec64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b3-b4-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>bd903fb7-9396-4242-8c9c-26aab8dd3708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b3-b3-b3-b4-Form1']/div/span/input</value>
      <webElementGuid>dc255a44-ddad-43a7-a8c8-6701d2c7a760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/aside/div[2]/div/form/div/span/input</value>
      <webElementGuid>74455acb-b3cb-410d-8d75-d9cfe1320188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b3-b4-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>c0b73f74-df1d-4d8b-9566-0e2a251af8ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
