<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Branch</name>
   <tag></tag>
   <elementGuidId>f8c7099a-0990-4a50-a08a-2f53d7ab59b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-BRANCH_DROPDOWN > label.mandatory.OSFillParent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-b1-b4-BRANCH_DROPDOWN']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f7b31c58-c733-4e27-aa21-9c9504a5876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatory OSFillParent</value>
      <webElementGuid>3ee20a55-b967-4423-824d-b3bcbad57c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>b3-b1-b4-Branch</value>
      <webElementGuid>b36f9e40-9a7f-405b-b0b3-0f979a26aae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Branch :</value>
      <webElementGuid>36e18fa8-7d2e-4d62-bb7a-7694f5c2b923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-BRANCH_DROPDOWN&quot;)/label[@class=&quot;mandatory OSFillParent&quot;]</value>
      <webElementGuid>ac5dcfaa-b94f-408c-bd1d-b4610dd6afcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-BRANCH_DROPDOWN']/label</value>
      <webElementGuid>6d4a85ad-a763-46ef-b9ea-3e89c7cc219a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Claim :'])[1]/following::label[1]</value>
      <webElementGuid>747f01f6-0cd7-4faf-80eb-90178031127e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Penugasan'])[1]/following::label[2]</value>
      <webElementGuid>c0ff2902-36f4-48b2-927e-1db98df5a9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/preceding::label[1]</value>
      <webElementGuid>0d357459-e530-47e3-b6af-e9313dba787f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::label[2]</value>
      <webElementGuid>fd4e096e-9e33-4f46-8e3e-57d0ea0994bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branch :']/parent::*</value>
      <webElementGuid>1fb267ee-3f04-4414-9354-68cbfd4d19a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>f80e81b0-eef6-40a6-91ff-85ccfe1b8f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Branch :' or . = 'Branch :')]</value>
      <webElementGuid>537b286f-457e-43a6-884f-50cbf762558e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
