<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiIQBAL PUTRA TAWAKALGIANDI _5675aa</name>
   <tag></tag>
   <elementGuidId>cc5d7fcb-b94d-4904-86b8-13461f7d8003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-Penugasan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b3-b1-b4-Penugasan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1a30a56-8a51-4cca-8f2c-8e037fe9adae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>7568f096-f275-45e8-8d46-bc1c5558a5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f65bbfc-008a-4139-998e-06745d661c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-Penugasan</value>
      <webElementGuid>21be2fb6-b160-41a9-ba1c-87378f833084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY</value>
      <webElementGuid>105eea5b-b794-454c-abe4-d02165c5b928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-Penugasan&quot;)</value>
      <webElementGuid>a65c8c98-0db1-4dcd-97f3-be2dd309cd5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-Penugasan']</value>
      <webElementGuid>cece0eff-f676-40e0-ad50-da13b0a33efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-Penugasan-container']/select</value>
      <webElementGuid>26dabe03-8121-48c7-b64b-7ee77a0392b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/following::select[1]</value>
      <webElementGuid>25ec568f-e5f5-4969-b6c4-831ad80a18e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch :'])[1]/following::select[2]</value>
      <webElementGuid>6171d818-e305-42a7-8e6a-057abe371e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::select[1]</value>
      <webElementGuid>8f04ce7b-743c-4cc3-b6fc-f1246b22f656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[1]/preceding::select[1]</value>
      <webElementGuid>4d5a33e3-e98e-42c2-86b9-1189e90af04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/select</value>
      <webElementGuid>12ce84df-bd41-413c-8891-98535b25cb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-Penugasan' and (text() = 'Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY' or . = 'Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY')]</value>
      <webElementGuid>12094d38-aca6-4654-96f1-ea90d2fc2a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
