<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSEMARANGSURABAYAJAKARTA GR_05f5b9</name>
   <tag></tag>
   <elementGuidId>897ceec0-39c8-4432-80fa-327b20870563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-Branch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b3-b1-b4-Branch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a51d0e6f-c5ef-4a04-bec7-348bc8b35b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>7141814d-7e7b-4fb8-b81f-c1e914d792d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5944f97a-1390-4644-a140-5564fa1b3c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-Branch</value>
      <webElementGuid>5400c856-86f9-4730-9945-b0d02afa2425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH</value>
      <webElementGuid>dc370132-7714-45ef-8d1c-4887f1d00976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-Branch&quot;)</value>
      <webElementGuid>8f408068-1c7c-438c-8855-296cb9ad33f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-Branch']</value>
      <webElementGuid>88ad86c7-d59c-465b-b7ea-a2623da51b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-Branch-container']/select</value>
      <webElementGuid>7ebd5ded-8c1e-4b6c-a778-775080c81979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch :'])[1]/following::select[1]</value>
      <webElementGuid>90d08d90-d131-4169-ae0b-9bdb9cb3743d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Claim :'])[1]/following::select[1]</value>
      <webElementGuid>e1573a33-2669-4c2e-9fff-a857d385644f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/preceding::select[1]</value>
      <webElementGuid>1d575377-7434-4927-b6e2-0bcedb983e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::select[2]</value>
      <webElementGuid>e890f783-a98e-44bf-ae5e-e69bc7572b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>07805ed9-49f8-4f07-86c6-4165f31464c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-Branch' and (text() = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH' or . = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH')]</value>
      <webElementGuid>01fdd4c5-fd48-4e3c-b5e1-2a6141e6f9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
