<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User-RBU-Flow-DEV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ece89572-2cde-46ec-9bc1-4962fdcb9326</testSuiteGuid>
   <testCaseLink>
      <guid>e45d6ca3-7a6a-4cbb-8c23-c37784127899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/SPV-RBU-Create-Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>89972975-534c-46b0-81fc-b9d7f3fa20ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/Staff-Assign-Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76cdd970-37e3-475d-ab79-7e2f87a25694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05ccc83b-d3d7-4b87-add4-574526b2d5bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73c20e7d-31b7-495a-9143-d4da755edb03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/Staff-Assign-Draft-1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e29ed1aa-ed8f-474b-96c3-55bc9021f375</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4cbdfc8-e744-4237-a77f-9451153f1e43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/Staff-Assign-Submit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bc8cd77-a53c-434e-8478-c61efa1078f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fcf701f-dd1e-4e89-b585-d7bf6f604ca3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/SPV-RBU-Persetujuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3c339d16-1351-4a58-a452-d04345503ebd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/SPV-RBU-Assign-PIC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>eee813e3-717d-4cf3-a769-18e5aa97ddbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/PIC-RBU-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cb3ab6f-9455-4445-9656-6d49d61415b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62463197-85e6-43ab-a276-d75aa3e2e637</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66a315b0-0eda-4bb5-9e05-77b96c088b55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/ENV-DEV/RBU/SPV-RBU-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
