<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  drop files orBrowseSupported form_3a2f15</name>
   <tag></tag>
   <elementGuidId>c72175e2-3fc9-48e3-b8cd-1f1fd504d68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-b4-dropzone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[1]/div/span/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a25c8509-aaa3-4d46-9708-1b9b75fa76a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-box-file drop-zone </value>
      <webElementGuid>55d75737-52a2-49a9-b828-69c79ad9ea5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-b4-dropzone</value>
      <webElementGuid>f92d9103-97af-4f5c-9446-c7bfdf269f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file</value>
      <webElementGuid>72de9ae8-1ac6-471f-bc77-2d584d2c9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-b4-dropzone&quot;)</value>
      <webElementGuid>e9c0932b-08eb-47ed-8fbc-807f8a4858d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-b4-dropzone']</value>
      <webElementGuid>2a9f4560-18a2-4a2e-930f-b892da9ca8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-$b4']/div/div</value>
      <webElementGuid>75c10e0f-634c-47b6-8ba9-d641d2d1c9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Dokumen'])[1]/following::div[4]</value>
      <webElementGuid>08568d9f-0395-42b5-8ffc-5f060aa0ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>b9d92e6f-b00b-4b25-a616-11bd0318d79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b1-b4-b13-b4-dropzone' and (text() = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file' or . = 'Drag &amp; drop files or BrowseSupported formats : xlsx,pdf,jpg,png,docxSelect file')]</value>
      <webElementGuid>cce54707-4ee7-4969-bc86-f7698fcaa14e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
