<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Baik_b3-b1-b4-b13-Input_Baik</name>
   <tag></tag>
   <elementGuidId>b4f39f5b-7f19-4e67-b665-8e49efb50ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-Input_Baik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[6]/aside/div[2]/div/div/form/div[3]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e38dcdb-78d4-48d5-8070-d0fb0a161516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>392ee77d-5c10-4876-a63e-47755f4edd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9774ed1-b655-4dcf-b589-14c1ea548e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3746056-c0a8-4e4d-854c-8b823993ce52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06d8a654-a876-4f36-9a39-27a90b14bef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-Input_Baik</value>
      <webElementGuid>5bad736f-7e9d-4a8d-ba5c-4ea45233a4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-Input_Baik&quot;)</value>
      <webElementGuid>caad32a8-9781-4552-a1e5-700ad1563830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b4-b13-Input_Baik']</value>
      <webElementGuid>ef31a083-037a-4610-affc-cd50caf70ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b3-b1-b4-b13-Form2']/div[3]/span/input</value>
      <webElementGuid>2e00a117-c85c-4291-b1bc-bb2018a6f11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>8bde47a9-5fbb-4b85-84f4-daec8dba5ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b1-b4-b13-Input_Baik']</value>
      <webElementGuid>efe0780c-6289-44cb-93a5-1a0efbfa07ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
