<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiCorporate Business UnitRet_46a7ca_1</name>
   <tag></tag>
   <elementGuidId>a95aca53-11c8-443b-8ea3-bd7394754889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[1]/div[2]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b1-DropdownBisnisUnit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bc1659b-94dc-468f-8334-5ca9bf0b0638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>71019e74-5ce7-472a-9fbd-aa3608e60d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d4de9c2-e9d0-4176-ac31-927d1bda3402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b1-DropdownBisnisUnit</value>
      <webElementGuid>cc359287-0571-4acf-99f1-218ebeca2351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiCorporate Business UnitRetail Business Unit</value>
      <webElementGuid>2c1f1609-67a4-452e-81ed-7aa52cd80bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b1-DropdownBisnisUnit&quot;)</value>
      <webElementGuid>bc27871b-ea9a-4b82-b95a-4f2821a3ab1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b1-DropdownBisnisUnit']</value>
      <webElementGuid>5e21b8d9-fd60-4ef3-8122-f9958131f90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b1-DropdownBisnisUnit-container']/select</value>
      <webElementGuid>82bff33f-7151-48c2-9731-9b51d854f0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::select[1]</value>
      <webElementGuid>cf4f1700-ff39-426a-b343-630ab6971450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisnis Unit'])[1]/following::select[1]</value>
      <webElementGuid>b3c503b1-fd11-453b-bf01-89933b9e40b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/preceding::select[1]</value>
      <webElementGuid>0c3b10d6-0170-4104-9e5c-1984e4acd441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/preceding::select[1]</value>
      <webElementGuid>2d0d38bf-4014-448b-901e-d319f7a98fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8ce04766-ad2a-4fbb-956a-703aa1d06cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b1-DropdownBisnisUnit' and (text() = 'Pilih OpsiCorporate Business UnitRetail Business Unit' or . = 'Pilih OpsiCorporate Business UnitRetail Business Unit')]</value>
      <webElementGuid>592b1f53-c0b4-4664-94cd-7d9c0c48170b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
