<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiTepatTidak Tepat_16</name>
   <tag></tag>
   <elementGuidId>09d38c5d-2b30-4efc-9562-3b5253ce39d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[12]/td[3]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b3-b8-l7_0-295_11-Kesesuaian3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81913960-e6e9-460c-a137-b11c67655fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>260fab61-14ce-4076-8fce-9a4497f4c177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c56277de-2d8c-4794-ab47-ee6bc47fddcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b3-b8-l7_0-295_11-Kesesuaian3</value>
      <webElementGuid>5395b08b-d460-474c-b75f-160d407f638a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiTepatTidak Tepat</value>
      <webElementGuid>0de5d466-8fdc-4a62-bcb3-a4d363ca0784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b3-b8-l7_0-295_11-Kesesuaian3&quot;)</value>
      <webElementGuid>64fbb214-b5ca-4786-bd2e-a292a03ec0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b3-b8-l7_0-295_11-Kesesuaian3']</value>
      <webElementGuid>35ef2713-e9db-419c-b6b8-62e87c45fa1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b3-b8-l7_0-295_11-Kesesuaian3-container']/select</value>
      <webElementGuid>0590c500-bf34-4b37-8394-12b22698325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota Pembelian Materai'])[1]/following::select[2]</value>
      <webElementGuid>e4d6a9a2-f3af-428a-9af4-d177961bb93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[36]/following::select[2]</value>
      <webElementGuid>dc5c277a-bdb1-4aff-aac7-f25af1e83692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[37]/preceding::select[2]</value>
      <webElementGuid>6ae563e1-8230-4cc6-addb-2929c2a43312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuitansi Pembayaran Uang Muka (DP)'])[1]/preceding::select[2]</value>
      <webElementGuid>b8baf163-ae18-4823-b568-9f6607e63dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[12]/td[3]/div/select</value>
      <webElementGuid>4529c91b-a9c8-45eb-bdb2-2111e2cab9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b3-b8-l7_0-295_11-Kesesuaian3' and (text() = 'Pilih OpsiTepatTidak Tepat' or . = 'Pilih OpsiTepatTidak Tepat')]</value>
      <webElementGuid>1861ae0f-e2f4-4307-8aad-b98a11c5048a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
