<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiBaikRusak_1</name>
   <tag></tag>
   <elementGuidId>d1e35f0e-b88c-461a-bc0e-e263d74c3e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[5]/aside/div[2]/div/div/form/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b11-Dropdown2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b63f7212-1d30-425f-8d2a-3944c63a3b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>29ccbf84-ed1d-4d65-be3b-b54186779449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eaf5b806-6bbd-4973-82df-1bcb1bb9cdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b11-Dropdown2</value>
      <webElementGuid>987b2b91-a50d-46c3-a072-b794d563be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiBaikRusak</value>
      <webElementGuid>ed1ba01a-a769-479c-9f27-0ec623b2d3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b11-Dropdown2&quot;)</value>
      <webElementGuid>b4cd7f61-2500-4482-ae0d-792cb87c10d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-b11-Dropdown2']</value>
      <webElementGuid>8fa04ca1-a0ff-4f2d-bb89-2f49da110b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b11-Dropdown2-container']/select</value>
      <webElementGuid>9c9417a0-288b-4502-a514-916c49487462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi'])[15]/following::select[1]</value>
      <webElementGuid>c2017cd4-073a-4564-b835-0502e397543d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keberadaan'])[20]/following::select[2]</value>
      <webElementGuid>ab8b21ad-1608-4b00-a7e7-b7eb0f8f6c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Temuan'])[20]/preceding::select[1]</value>
      <webElementGuid>69e56bc6-326c-4e0c-ac9e-f47f0c3b97a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[20]/preceding::select[2]</value>
      <webElementGuid>40cb0d2d-7e6d-4b39-84fc-815427a656cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>21010715-7afa-4d3f-8fa7-a018f15d8a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-b11-Dropdown2' and (text() = 'Pilih OpsiBaikRusak' or . = 'Pilih OpsiBaikRusak')]</value>
      <webElementGuid>ca96764e-2a3d-4655-ba32-26d58ed01724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
