<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan_b3-b1-b4-TextArea_Remarks</name>
   <tag></tag>
   <elementGuidId>c5b3ea1d-a702-4b64-b094-ec758f1f8fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[4]/div/div[1]/div[3]/div[2]/div[1]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-TextArea_Remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>755e1f58-d2c1-44a1-a8a2-7f38efe8d453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>fc743f0b-b66c-457e-a489-031322f62811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>debc43a6-32f7-4934-bb87-a10bf22a57d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>64e01de5-9796-441f-90e1-41084ba5a04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-TextArea_Remarks</value>
      <webElementGuid>98d8ea1a-17ea-4380-8190-a0c6be720ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-TextArea_Remarks&quot;)</value>
      <webElementGuid>9a19c65c-6059-4d40-911b-d3672ed170a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b1-b4-TextArea_Remarks']</value>
      <webElementGuid>f952db0c-7b64-4844-a58e-b33408eaad7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-$b4']/div/div[3]/div[2]/div/span/textarea</value>
      <webElementGuid>1cde4f26-0ed2-4013-b755-024b2ca5a0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9292e49d-bcf6-4f90-a757-2082681ccc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b1-b4-TextArea_Remarks']</value>
      <webElementGuid>10075c71-8476-4029-867e-36878e5f45bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
