<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  drop files orBrowseSupported form_12d9d4_1</name>
   <tag></tag>
   <elementGuidId>38886a56-aa64-44d9-a9d7-2f5742f12cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[1]/div/span/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b2-l1-122_0-b20-b5-b4-dropzone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fc3d836-ef1e-45ce-bab4-c1a46cc8f61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-box-file drop-zone </value>
      <webElementGuid>98cb71ec-cebf-4838-90c9-64cc94d99b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b2-l1-122_0-b20-b5-b4-dropzone</value>
      <webElementGuid>600e9b6f-9ae8-4a8e-82a6-8ce4fb723cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file</value>
      <webElementGuid>8f330405-5bfa-4fbd-b557-cf90da533f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b2-l1-122_0-b20-b5-b4-dropzone&quot;)</value>
      <webElementGuid>6a4d18a7-7145-479b-b494-6faa93f40b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b2-l1-122_0-b20-b5-b4-dropzone']</value>
      <webElementGuid>df8b3bf4-556f-4bd7-9eef-3ca110674f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b2-l1-122_0-b20-b5-$b4']/div/div</value>
      <webElementGuid>83653051-1234-4beb-a56d-054e9417df7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Dokumen'])[1]/following::div[4]</value>
      <webElementGuid>4ad4c34c-0097-4679-99c3-3c6cc002e8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>7d4dca61-179a-438f-8538-e687367747df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b3-b2-l1-122_0-b20-b5-b4-dropzone' and (text() = 'Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file' or . = 'Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file')]</value>
      <webElementGuid>9b93d744-64e1-41c6-b75a-7e9f5ba31198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
