<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  drop files orBrowseSupported form_12d9d4_2</name>
   <tag></tag>
   <elementGuidId>9b1f8a00-9790-44b7-b9ce-95fc3de3e0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[2]/div/div[1]/div/span/label/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b3-b4-b4-dropzone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06eb3ab8-d8b8-4aec-8005-0cad1cc6614a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-box-file drop-zone </value>
      <webElementGuid>4e3b5958-8d29-4654-929a-ec494b27c9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b3-b4-b4-dropzone</value>
      <webElementGuid>0706f1a3-6e50-42a4-ae33-9d2d2a8cdf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file</value>
      <webElementGuid>099c2765-f671-4e0f-aa25-b071b44e09ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b3-b4-b4-dropzone&quot;)</value>
      <webElementGuid>aabedc28-ccbc-4d19-b01d-a3ad6afff70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b3-b4-b4-dropzone']</value>
      <webElementGuid>af0bb062-6a28-41a0-bb3f-f4373c80205b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b3-b4-$b4']/div/div</value>
      <webElementGuid>413fbe2c-d41f-4053-90fc-46d21e75bc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Dokumen'])[1]/following::div[4]</value>
      <webElementGuid>46fcf930-7387-4cb3-af3d-e0ba9c23771c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>16158ca4-88c0-4c7f-9bf5-a2a4bb20cce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b3-b3-b4-b4-dropzone' and (text() = 'Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file' or . = 'Drag &amp; drop files or BrowseSupported formats : png,jpeg,jpg,img,doc,docx,xls,xlsx,ppt,pptx,pdfSelect file')]</value>
      <webElementGuid>a8f430ec-bd49-4b83-905a-b3a9fcf9cc17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
