<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenggat Waktu Penyelesaian_b3-b3-b3-b_9a858d</name>
   <tag></tag>
   <elementGuidId>961cd159-2417-444c-88a4-f426493a2d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[3]/div/div[2]/div/aside/div[2]/div/form/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b3-b4-TenggatWaktuPenyelesaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb9db088-d11d-413b-94a0-e921b2360cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>740198eb-8e21-4f8c-84d3-1bf3766811f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6b660f06-f7da-4a9b-af3a-9786b5be9013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f7e6a51-6bc5-4471-9b47-c5134024669a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b3-b4-TenggatWaktuPenyelesaian</value>
      <webElementGuid>5de53f89-6e01-498d-9245-43cb80dd9a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b3-b4-TenggatWaktuPenyelesaian&quot;)</value>
      <webElementGuid>23398109-255c-4c1f-8963-8a33b21b8e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b3-b4-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>3c9731c2-9397-4958-8296-ac696d7651ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b3-b3-b3-b4-Form1']/div/span/input</value>
      <webElementGuid>9c17d31d-8aa1-4239-850d-97478d95a7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/aside/div[2]/div/form/div/span/input</value>
      <webElementGuid>1beef578-7c25-41cb-89f0-db6ceb44e034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b3-b4-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>0629b66d-5996-4b3a-ad0a-0c0691ecb94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
