<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenggat Waktu Penyelesaian_b3-b3-b2-l_cf3a97</name>
   <tag></tag>
   <elementGuidId>b31273fb-b494-4e26-9894-b8e5c6f8036a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div/div[1]/div[2]/div/div/div/div/div/div[2]/div/div[9]/div[2]/div/aside/div[2]/div/form/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b2-l1-122_0-b20-b5-TenggatWaktuPenyelesaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70c369a9-0802-474f-9f44-82acbe16b8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d021d87d-685b-4873-b177-4ad13fdf3724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f3fc0430-544f-4857-8795-7397f6bb4c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e1d466c-bc21-48ac-92f1-e6cae088e4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b2-l1-122_0-b20-b5-TenggatWaktuPenyelesaian</value>
      <webElementGuid>5c352386-7e0e-4b90-bb0a-e520cd52962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b2-l1-122_0-b20-b5-TenggatWaktuPenyelesaian&quot;)</value>
      <webElementGuid>3e8470fd-4c49-459b-af9e-40f21682b659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b2-l1-122_0-b20-b5-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>a2d5d021-b0e9-4868-9289-c2299ed3b020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='b3-b3-b2-l1-122_0-b20-b5-Form1']/div/span/input</value>
      <webElementGuid>ae8c8510-04d9-47c7-aa04-804a4838cbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/span/input</value>
      <webElementGuid>11f1bf7b-ab7a-43dd-957a-3cc85c59f285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b2-l1-122_0-b20-b5-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>9fa3927d-765c-4469-91d6-a5a7ce0eaadd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
