<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 65,000.00_b3-b4-b6-l4_0-352_0-Inpu_9ea4a2</name>
   <tag></tag>
   <elementGuidId>50814ca1-b47e-43cb-bcd2-157cca401076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-352_0-Input_TanggalTransaksiKwitansi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[1]/td[6]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f5c89f0-6df6-4df3-a3af-4c0bd9229bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>da25cef2-1ab2-485a-ab9f-81d5a0600453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>a625eeb3-8874-4678-95ef-3d1846a390c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>381909d2-e04b-4cba-893b-9817adcfd05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-03-16</value>
      <webElementGuid>89086b70-dd74-4373-8feb-1a18143dc36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-352_0-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>96c7e17f-4721-4520-87fb-cd78e2c0460f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-352_0-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>c344ed74-30fb-4609-af2f-0612e5052170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-l4_0-352_0-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>e49caf79-bae1-472c-8fc9-85753e8a6cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b4-b6-TableReimbursed']/tbody/tr/td[6]/div/span/input</value>
      <webElementGuid>24269dd1-b668-4ab1-9b02-79117a5c6797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/span/input</value>
      <webElementGuid>04d91aff-dd89-48f9-b2e9-55f36ee925d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b4-b6-l4_0-352_0-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>30ce6bc8-10d2-413a-9319-8e7ee21ce498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
