<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BARU_b3-b1-b6-l2_0-222_0-TenggatWaktu_87afb6</name>
   <tag></tag>
   <elementGuidId>5bd2aa6f-ae73-4b84-8d55-941d43595ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[1]/div/div/table/tbody/tr[1]/td[16]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b6-l2_0-222_0-TenggatWaktuPenyelesaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>823169fa-579d-4018-a857-c9016831452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>5366b263-f878-408e-82b4-e56e0a02bde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>91f5a2e0-3b35-4eae-bb0d-e12ede400b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b085599-fcff-46a5-98cd-66405cd4f0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b6-l2_0-222_0-TenggatWaktuPenyelesaian</value>
      <webElementGuid>716ad58e-8e8c-4f60-abe8-4b12512e4968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b6-l2_0-222_0-TenggatWaktuPenyelesaian&quot;)</value>
      <webElementGuid>78d3be95-cba0-4ae5-a3d6-5a43c26d2d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b6-l2_0-222_0-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>f29e57c7-796c-4250-9b48-3a5803174748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b6-PettyCash']/div/div/table/tbody/tr/td[16]/div/span/input</value>
      <webElementGuid>8850cac9-be69-4948-ad42-8ed7b8f554ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/div/span/input</value>
      <webElementGuid>6283d403-37c5-439b-ade5-1371b6408175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b6-l2_0-222_0-TenggatWaktuPenyelesaian']</value>
      <webElementGuid>c86a9241-565c-4aa5-828c-d00d922895be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
