<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang</name>
   <tag></tag>
   <elementGuidId>79043070-968d-4735-b605-7b7db327998e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43da9e7f-6c36-470b-87cb-8357ba3c14a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>8091816e-d246-4d01-a31a-51e2d4ea8e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader</value>
      <webElementGuid>98050136-e238-4a29-86df-21ff4fa40542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd600889-aa9e-4470-aee6-00854f6943e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87e3bfa1-0bc1-4169-ab0f-673525f64a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_1-b4-l1-23_5-b1-Items</value>
      <webElementGuid>82c98a75-5a6f-4245-911d-8ee938490315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4070e544-b4d1-43c7-9a69-83b0e4fdb88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12b0134d-afd8-4cf3-bc6d-f092117d5040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional Cabang</value>
      <webElementGuid>7f598771-d875-46e1-aa7f-7f8bbe31a405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader&quot;)</value>
      <webElementGuid>df737e67-065a-430c-87da-386cc25c9819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader']</value>
      <webElementGuid>ed5c4601-e5cf-44e4-a151-184a58382f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_1-b4-l1-23_5-b1-Submenu']/div</value>
      <webElementGuid>b15dd8bf-24b7-4ec6-a280-5b7ab34d0b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom/Supplier'])[1]/following::div[4]</value>
      <webElementGuid>92b98932-812d-4635-9de0-8fba805ca80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/following::div[4]</value>
      <webElementGuid>7e5d2980-c778-4dc8-a986-533c9ede5df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petty Cash'])[1]/preceding::div[3]</value>
      <webElementGuid>f63953e6-c36f-4cd0-9567-b615a0f0fa65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>99fb94c8-d3ca-4090-87fd-9da2b6b31c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader' and (text() = 'Operasional Cabang' or . = 'Operasional Cabang')]</value>
      <webElementGuid>59927515-e26b-42c4-a6cb-5343720d96d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
