<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiTepatTidak Tepat_5</name>
   <tag></tag>
   <elementGuidId>6e3980bc-2e83-4bd6-8651-41ca989eb236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[6]/td[3]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b3-b6-l8_0-424_12-Kesesuaian3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9287752-d390-4bdb-bf0b-1daf442047e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>45cbb5a8-213c-4792-b51d-2fa4cb640b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6befb50f-5738-4a68-b8f2-efc8e39013ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b3-b6-l8_0-424_12-Kesesuaian3</value>
      <webElementGuid>85763ec4-fcde-424a-ad5a-f1fc32748a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiTepatTidak Tepat</value>
      <webElementGuid>f90fb0b1-dd94-44a8-82d4-dd58da5d4111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b3-b6-l8_0-424_12-Kesesuaian3&quot;)</value>
      <webElementGuid>8b154a3f-cf95-47a5-84be-60e0f4a01b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b3-b6-l8_0-424_12-Kesesuaian3']</value>
      <webElementGuid>7863a27f-21e2-4a15-917b-dbee17236f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b3-b6-l8_0-424_12-Kesesuaian3-container']/select</value>
      <webElementGuid>789d854d-105c-415d-ba0d-fa8d68e6e791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETTY CASH SLIP'])[1]/following::select[2]</value>
      <webElementGuid>ef83fea6-402d-4e0a-9147-4ac4d511f8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[20]/following::select[2]</value>
      <webElementGuid>f485da47-59f2-4468-b1b1-a1bb2338c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[21]/preceding::select[2]</value>
      <webElementGuid>a0e524d6-b070-4823-a53b-0717da826b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Transaksi'])[3]/preceding::select[2]</value>
      <webElementGuid>b90454d7-0b9b-40c8-8c58-571b75407b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]/div/select</value>
      <webElementGuid>3de42b86-1f80-4691-af43-1ceffc142a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b3-b6-l8_0-424_12-Kesesuaian3' and (text() = 'Pilih OpsiTepatTidak Tepat' or . = 'Pilih OpsiTepatTidak Tepat')]</value>
      <webElementGuid>87e87239-6e04-4d31-9e02-e6c4bb3e1362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
