<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiAdaTidak Ada</name>
   <tag></tag>
   <elementGuidId>7c2136ae-de3a-442e-bde7-5cbd6b22288f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[3]/div/div/div[6]/aside/div[2]/div/div/form/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-b13-Dropdown1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d482c033-37d1-4a63-b88c-316268f9fb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>a79f698c-e3c9-4960-9bdb-09148f94dc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd63281a-9ddb-4199-a5b3-d4f6c30ea0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-b13-Dropdown1</value>
      <webElementGuid>21aaffd7-181e-4163-93cb-d86028a840df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f497c757-4379-4c0d-a3c8-e4bf30db6dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiAdaTidak Ada</value>
      <webElementGuid>73df18fc-5438-4760-b563-fb88218d32fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-b13-Dropdown1&quot;)</value>
      <webElementGuid>7aaab675-d702-422d-b9a3-98799f8a91b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-b13-Dropdown1']</value>
      <webElementGuid>94b6020d-d074-4286-9e3d-181c1f81d3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-b13-Dropdown1-container']/select</value>
      <webElementGuid>c2fb5c33-87cc-4232-b392-a208c9066bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keberadaan'])[19]/following::select[1]</value>
      <webElementGuid>889a05c8-1600-40b9-a6ab-9801782e89cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fasilitas - Meja'])[1]/following::select[1]</value>
      <webElementGuid>690a7da1-8470-4650-bf9f-e7c130644e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lantai'])[5]/preceding::select[1]</value>
      <webElementGuid>82f5825c-3870-46dd-8f24-0d43795ddb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baik'])[12]/preceding::select[2]</value>
      <webElementGuid>3290dbbe-4d85-498a-a3c5-d705fc13dcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/aside/div[2]/div/div/form/div/div/select</value>
      <webElementGuid>74158a9c-3f2c-4409-88ce-f402b715c0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-b13-Dropdown1' and (text() = 'Pilih OpsiAdaTidak Ada' or . = 'Pilih OpsiAdaTidak Ada')]</value>
      <webElementGuid>2bb248ab-be99-4df6-ad29-0d7d5b9e0e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keberadaan'])[12]/following::select[1]</value>
      <webElementGuid>4bf5836b-3434-412f-b016-2537a79f0faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Fasilitas - Mesin Tik'])[1]/following::select[1]</value>
      <webElementGuid>11ee7159-e91c-4806-ab1e-a23c6d88251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lantai'])[6]/preceding::select[1]</value>
      <webElementGuid>4af2cc18-e6d3-4ce9-b319-34d65194ee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baik'])[14]/preceding::select[2]</value>
      <webElementGuid>c8862d3f-c510-4ed4-a078-967dcb7772b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
