<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apakah anda yakin ingin melanjutkan ke _5a6b21</name>
   <tag></tag>
   <elementGuidId>379711f3-42dc-4e67-8ad8-78d9cca94d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popup-dialog.popup-dialog.popup-notif2.popup-confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Development CSULFinance'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48b87a52-90a4-4227-bb0e-fff07780a7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-dialog popup-dialog popup-notif2 popup-confirmation</value>
      <webElementGuid>1f1b3799-d01d-4837-9cd2-3ce20469060f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>68e30cad-b9fc-411a-bc16-76f08fe803fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98dff567-9746-45a0-85fd-5c83f6e5ad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin ingin melanjutkan ke proses Persetujuan ? Data tidak dapat diubah setelah proses iniCancelSubmit</value>
      <webElementGuid>cc9ff47b-7d95-46d2-99a3-a63d4d5ce7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;popup-disable-scroll&quot;]/body[@class=&quot;windows chrome os-dark-mode is-ltr desktop landscape&quot;]/div[@class=&quot;portal-class&quot;]/div[1]/div[@class=&quot;popup-backdrop&quot;]/div[@class=&quot;popup-dialog popup-dialog popup-notif2 popup-confirmation&quot;]</value>
      <webElementGuid>a136541f-9eff-4ff6-8fe8-f43a50bb3ebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Development CSULFinance'])[1]/following::div[4]</value>
      <webElementGuid>e482f7fd-c02c-4db6-a55b-27ac390c786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Designed &amp; Developed by'])[1]/following::div[4]</value>
      <webElementGuid>980ea7dc-72b6-4fa2-9fc7-58310d2c376c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>dddfb060-fe91-4ac0-b8e0-bb8623420cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apakah anda yakin ingin melanjutkan ke proses Persetujuan ? Data tidak dapat diubah setelah proses iniCancelSubmit' or . = 'Apakah anda yakin ingin melanjutkan ke proses Persetujuan ? Data tidak dapat diubah setelah proses iniCancelSubmit')]</value>
      <webElementGuid>f688ad78-7116-463a-ac89-1c2e897ec213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
