<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tindak Lanjut</name>
   <tag></tag>
   <elementGuidId>51be9533-ae49-4c55-b98f-14fb41adf737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-17_10-b3-Menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-l1-17_10-b3-Menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b111a5a-4e60-401f-865a-6564f9ead84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__item</value>
      <webElementGuid>bebc2384-90e0-4a89-8d64-0802f219e367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_10-b3-Menu</value>
      <webElementGuid>3ec7968a-af71-49be-b0c7-1aa76e65e7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tindak Lanjut</value>
      <webElementGuid>705b0f46-5c32-4a57-9855-0167dd23e34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-17_10-b3-Menu&quot;)</value>
      <webElementGuid>e58ef527-efdc-42c7-88a9-96c0c0c1387e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_10-b3-Menu']</value>
      <webElementGuid>70045fc7-d215-402a-ad12-f572ca14943d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_10-b3-SubMenuHeader']/div</value>
      <webElementGuid>5b31ba40-f93c-44fb-84df-3929d13aad81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemeriksaan Aset Tarikan'])[2]/following::div[5]</value>
      <webElementGuid>bd44d5d5-c429-4fc7-9d5c-2f6383c91b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas &amp; Surat Kuasa'])[2]/following::div[5]</value>
      <webElementGuid>465e826f-42db-4123-b0af-5ba195b7c688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akuisisi'])[3]/preceding::div[2]</value>
      <webElementGuid>6a207387-ea01-494a-a663-46065a834cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>763173f7-e1d4-43b2-87de-87936550886f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_10-b3-Menu' and (text() = 'Tindak Lanjut' or . = 'Tindak Lanjut')]</value>
      <webElementGuid>243a5cf4-6845-4c62-b134-9c5ca9121a73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
