<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan_b3-l1-1475_0-b2-TextArea_Remarks</name>
   <tag></tag>
   <elementGuidId>70d6cf19-3856-43cd-912b-933152367fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[2]/div/div/div/div/div[3]/div[2]/form/div/div/div[2]/div/div/div[2]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-1475_0-b2-TextArea_Remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5c00f2e1-fa32-4fe4-8a7a-05093ee95ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>b29de587-1aea-45db-862d-fb1bfe8a2716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9e24dfdc-7319-4f36-8509-fa09ba4aefb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>5455644c-3b87-4d69-8176-65304104f1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-1475_0-b2-TextArea_Remarks</value>
      <webElementGuid>66cffefd-16ca-4c88-944a-e2625db4d658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-1475_0-b2-TextArea_Remarks&quot;)</value>
      <webElementGuid>733ec4cd-31e7-4653-a4e2-0298622133c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l1-1475_0-b2-TextArea_Remarks']</value>
      <webElementGuid>aa743aaa-f073-4e0e-add0-5cb2c6b65121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-1475_0-b2-b13-Column2']/span/textarea</value>
      <webElementGuid>bdb5bf6b-51e2-4f58-a68a-611d2f3daa4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6732195f-50f4-4083-98dd-2c16b705ddcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l1-1475_0-b2-TextArea_Remarks']</value>
      <webElementGuid>e5f03968-328b-4604-b449-23e705e429e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
