<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User-CBU-Flow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>07267f88-e1ce-41c8-ba03-c2a723279226</testSuiteGuid>
   <testCaseLink>
      <guid>44f1e3dd-3699-4422-9767-748c3d883ee6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/SPV-CBU-Create-Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>04cb59af-810b-4b34-9073-d58892a387eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32c74dc8-7c9e-44a1-9067-ca25aae7a794</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f203915-4fd2-42f9-9837-d8f4fc4330f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39939092-1334-4761-b737-937d25cef1ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b2003e-c9b8-4c4f-b10a-319124f63245</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8536d8b9-9863-48dc-934d-b3ab0195f620</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c92febac-570a-4f69-b272-17989034e7d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed855a98-5fff-4ac2-a440-0714863f7a4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef2ef3f4-110c-4912-adf9-0c8d0c16f853</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ee9a90e-5f4f-48a9-bbcd-9e5b55dfdaca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>318dccf8-d79f-48a2-aa3c-6c75b32a7340</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ad9c6da-58a9-4fa2-80e7-34e6e69686a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-6</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6da9ec83-c450-42df-aa23-d7f3175bd7d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e98467bd-3633-44cc-b4dd-320c3a8b30c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aac484a-1976-4c24-9367-cf94d8ca4a02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4abba519-7f9c-4e79-b2b0-b6c9b124215f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-8</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38ac2d7d-8980-45ca-ab2f-ed8117933412</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12cc1b5c-54bc-419a-9768-a5e213ce9a26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-9</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbe55be8-f649-42c4-8567-7676f72fde8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21703d16-fccc-4f58-97bf-cddff48fc968</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6756dfe-2a77-4f2b-9c9f-86df3ad863d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00a299cd-240b-422d-ab5e-5e30ea2d1e87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5926982-5599-4628-afaa-e7b854848204</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ec1fbe2-652f-4664-ae7b-0826b1f4d6aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc252de-b59d-4395-897c-279e98f3dc31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>983c7f20-3722-41b1-ada5-006fbf53e59c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e5f206-de45-4b7b-b99c-85c0238fab94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>834e8713-0858-454a-94e3-22d869eac82a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3fdd03d-d033-4a15-b190-40c62d60cefe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a1d345f-ca41-41b7-b3e4-7607ed7eb0d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8421bd7-9482-4f53-b8e8-81bee52b94ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9e5ceec-10f1-41c9-bc1b-350fb8659d57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ccbb36-a3b6-40ac-9a80-1edfe4f92488</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1432874-ff02-4f84-913f-8b092f36cb4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60796e17-9fe7-4086-ba34-d2612e41445e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34ca7521-2a7d-405c-80ed-df0f90169976</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2e10628-236c-40ee-8023-8942cf717223</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c001f90-0b82-4af3-a8ac-3558f49331bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e06cd1d6-9b67-4519-9838-ed20fd575af0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc3899d0-bf17-4563-a004-3602cd063bac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e8b3aea-f0eb-4391-8054-f049cb2b475e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29b23914-f875-4f91-bb18-66ad815a4b1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72c427be-09d8-4b35-ac6b-32963d7ba65f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c18e2bd4-f3c6-4247-8110-6202a19fbc4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-22</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>708a0063-5ac6-4abd-8dfd-6342b7c0780b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af01ef75-0085-43f4-91e7-875491c27533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/Staff-Assign-Draft-23</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d716058a-875c-4911-bc1e-fcfc17fbc056</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83c18745-571f-4cd0-81e4-2aa260a1316c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/SPV-CBU-Persetujuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6fa10faf-f0ea-44fe-8174-4d9609aa6e80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/SPV-CBU-Assign-PIC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>146ffc00-0a66-4982-b725-7b880f586045</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/PIC-CBU-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>423b4762-ffac-4a27-9ff8-ac473d46511f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3dcd3d9-217c-43c5-b7c8-6445efa815a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-2/CBU/SPV-CBU-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
