<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BARU_b3-b1-b6-l4_0-231_1-TenggatWaktu_606dee</name>
   <tag></tag>
   <elementGuidId>d3c3a2c2-3827-42c9-a283-0c790fb4c502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr[2]/td[9]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b6-l4_0-231_1-TenggatWaktuPenyelesaian2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01c07724-49ea-43fd-8c0b-d6fed7e8f001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d407e9d2-8815-4250-95b1-57b074f0f5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>dbe4611c-9d33-41ec-aa42-94a2c7d8a7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>990e5295-5733-4ef0-ac20-ffe9a25103ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b6-l4_0-231_1-TenggatWaktuPenyelesaian2</value>
      <webElementGuid>c1f97620-4342-4081-9391-35bfc21d8796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b6-l4_0-231_1-TenggatWaktuPenyelesaian2&quot;)</value>
      <webElementGuid>bfd01a91-4e86-47fa-bffc-21e89eecd482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b6-l4_0-231_1-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>a292a93f-03b0-49a5-b13a-6a131ab8034e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr[2]/td[9]/span/input</value>
      <webElementGuid>cbff7502-3128-4e01-b531-8e9c40e1ac58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/span/input</value>
      <webElementGuid>951f6797-6b08-4002-88ac-10a52a0ebac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b6-l4_0-231_1-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>6dbe21f8-9790-4536-aea7-5762a3206b6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
